default: &default
  google:
    engine_id: <%= ENV['GOOGLE_ENGINE_ID'] %>
    api_key: <%= ENV['GOOGLE_API_KEY'] %>

  bing:
    subscription_key: <%= ENV['BING_SUBSCRIPTION_KEY'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
