default: &default
  google:
    engine_id: <%= ENV['GOOGLE_ENGINE_ID'] %>
    api_key: <%= ENV['GOOGLE_API_KEY'] %>

  bing:
    user_agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36'
    subscription_key: <%= ENV['BING_SUBSCRIPTION_KEY'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
